### ISSUE TITLE
Configure internetarchive in program

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [9021007/IPAUploader#1]
Here's a small script that verifies that you're logged into the internetarchive tool, and configure it if it's not configured.

```python
import internetarchive as ia

if (not ia.get_session().access_key) or (not ia.get_session().secret_key):
    print("Please enter your Internet Archive login credentials")
    ia.configure()
````

I believe this would be better instead of requiring the user to run `ia configure` before, they can just configure it after running the program.

Also, I'm pretty sure you don't need to do `brew install internetarchive`, you can just install it through pip, which would be one less command to run (since it's already being installed with `pip install -r requirements.txt`).

**Comment by 9021007** [comment]
That's a great idea! I'll add that next time I work on the script.
